# Generated by Django 2.2.13 on 2020-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
