# Generated by Django 2.2 on 2021-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='文章标题'),
        ),
    ]
